import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import { Header } from "@/app/components/header";
import React from "react";
import { PageProvider } from "@/context/pageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <PageProvider>
            <main className="w-auto">
              <Header />
              {children}
            </main>
          </PageProvider>
        </Providers>
      </body>
    </html>
  );
}
